apiVersion: skaffold/v2beta17
kind: Config
deploy: 
  kubectl:
    manifests: 
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: semiotic-tracer-318406
  artifacts:
    - image: shivdon/auth
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: shivdon/client
      context: client
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: '**/*.js'
            dest: .
    - image: shivdon/tickets
      context: tickets
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: shivdon/orders
      context: orders
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: shivdon/expiration
      context: expiration
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: shivdon/payments
      context: payments
      docker: 
        dockerfile: Dockerfile
      sync:
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    